spring:
 h2.console:
  enabled: true
  path: '/console'
 datasource:
  url: 'jdbc:h2:file:D:/Udemy-kursy/todo-tasks/todo-db'
  username: adminAB
  password: kokos
management:
 endpoints:
  web:
   exposure:
    include: '*'

